
spring:
  #jpa配置
  #数据库连接配置
  datasource:
      #MSSQL
      url: jdbc:sqlserver://localhost:1433;DatabaseName=testCore
      username: sa
      password: wizbank
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      tomcat:
          max-wait: 10000
          max-active: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mybatis:
      mapperLocations: classpath:mapper/*.xml
      type-aliases-packag: com.text.spring.boot.doamin
server:
  port: 8901
